version: '3'
services:
  server:
    build: ./server
    ports:
      - "4000:4000"
    restart: always
    container_name: server
    networks:
      - my-networks
  my-mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    restart: always
    container_name: my-mongodb
    volumes:
      - ./data:/data/db
    networks:
      - my-networks
networks:
  my-networks:
    driver: bridge

