version: '3'
services:
  server:
    build: ./server
    ports:
      - "4000:5000"
    restart: always
    environment:
      PORT: 5000
      MONGO_INITDB_ROOT_PASSWORD: shahrear
      MONGO_URI: mongodb://shahrear:shahrear@mongo:27017/
    depends_on:
      - mongo
  mongo:
    image: mongo:latest
    restart: always
    container_name: my-mongodb
    volumes:
      - ./data:/data/db
    networks:
      - app-net
networks:
  app-net:


